CREATE TABLE concerts  
(
  concert_id  INTEGER PRIMARY KEY generated by default AS identity,
  concert_name    VARCHAR(255) NOT NULL DEFAULT 'no song title',
  concert_date    DATE NOT NULL,
  artist INTEGER REFERENCES artists(artist_id) NOT NULL -- Foreign key
);

